name: Update Following Count
on:
  schedule:
    - cron: "0 * * * *"  # 每天更新一次
  workflow_dispatch:  # 支持手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get Following Count
        run: |
          FOLLOWING=$(curl -s "https://api.github.com/users/JustFollowThem" | jq -r '.following')
          CURRENT_TIME=$(date +"%Y-%m-%d %H:%M:%S")
          CST_TIME=$(TZ='Asia/Shanghai' date +"%Y-%m-%d %H:%M:%S")
          sed -i "s#<!-- FOLLOWING_COUNT -->.*<!-- FOLLOWING_COUNT -->#<!-- FOLLOWING_COUNT -->$FOLLOWING<!-- FOLLOWING_COUNT -->#g" README.md
          sed -i "s#<!-- LAST_UPDATED -->.*<!-- LAST_UPDATED -->#<!-- LAST_UPDATED -->$CURRENT_TIME<!-- LAST_UPDATED -->#g" README.md
          sed -i "s#<!-- LAST_UPDATED_CST -->.*<!-- LAST_UPDATED_CST -->#<!-- LAST_UPDATED_CST -->$CST_TIME<!-- LAST_UPDATED_CST -->#g" README.md
          
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update following count"
          git push
